### PR TITLE
seasonal blog post

### PR DESCRIPTION
**Pull request by christophsax**
Next try.

Let's wait a bit with this for @DivadNojnarg to promote his post first.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
The CICD got stuck somehow, had to restart it on a new commit. Seems ok now. About the preview, it seems that the action is slightly different that what we have (not sure if this explains our issue): https://github.com/quarto-dev/quarto-actions/tree/main/publish#rendering-with-a-quarto-profile.

**Comment by christophsax** [comment]
Aaaahh, it's always at: https://cynkra.github.io/cynkrablog/

As it says in the README...

image

**Comment by christophsax** [comment]
@DivadNojnarg What would be a good date to publish? E.g., Friday? Or should we wait longer after your post?

**Comment by DivadNojnarg** [comment]
@christophsax even tomorrow is ok. Up to you ;)

**Pull request merged**
