### PR TITLE
init blockr article

### PR DESCRIPTION
**Pull request by DivadNojnarg**
@christophsax Just FYI. A new blog post in preparation.

### CODE REVIEW

**Comment by christophsax** [comment]
Cool, that's very nice! Perhaps @nbenn would be the better reviewer?

Why don't we have a preview anymore?

Do you want to publish this first? Fine for me, but you could also publish shortly after my one.

**Review by christophsax — APPROVED** [review]

**Comment by christophsax** [comment]
On the website, I see:

image

> Why don't we have a preview anymore?

We would have spotted it there, I guess. @DivadNojnarg

**Comment by christophsax** [comment]
Same in the Shinymobile post

image

**Comment by DivadNojnarg** [comment]
It's working well for me (just updated chrome + cleared my cache). I don't know about the preview. is it this workflow step?

```shell
- name: Deploy gh-pages Preview
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.title, 'chore(deps):') }}
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          QUARTO_PROFILE: preview
```

**Comment by christophsax** [comment]
AccessDenied is a Safari thing, it works in Firefox.

We used to have a preview link in PRs, I don't know when it was gone.

**Pull request merged**
