### PR TITLE
fix: simplify URLs

### LINKED ISSUE #38: Remove blog in URL?
probably weird to have blog.cynkra.com/BLOG?

### PR DESCRIPTION
**Pull request by maelle**
Fix #38

### CODE REVIEW

**Comment by maelle** [comment]
@pat-s I do not understand lychee output here.

**Comment by maelle** [comment]
@pat-s would you mind reviewing this before the redirect is set up?

**Review by pat-s — APPROVED** [review]
LGTM, lychee might be solved by #44?

**Review by christophsax — APPROVED** [review]

**Comment by maelle** [comment]
I'll try merging, will fix if it still breaks on main.

**Pull request merged**
